### ISSUE TITLE
Kolos z matmy

### ISSUE THREAD

**Issue by kerps1** [kerps1/Szkola#1]
**Materiały, dział Algebra:**
http://matematykadlastudenta.pl/

**Zadanka:**
http://users.pja.edu.pl/~denisjuk/al/cw/z1-geometria.pdf
http://users.pja.edu.pl/~denisjuk/al/cw/z2-uklady.pdf
http://users.pja.edu.pl/~denisjuk/al/cw/z3-matryksy.pdf
http://users.pja.edu.pl/~denisjuk/al/cw/z4-przestrzen.pdf
http://users.pja.edu.pl/~denisjuk/al/cwiczenia/06-wyznaczniki.pdf
http://users.pja.edu.pl/~denisjuk/al/cwiczenia/07-liczbyZespolone.pdf

**Przykładowy kolos:**
http://users.pja.edu.pl/~denisjuk/al/testy/kolokwium_2011_11_20.pdf
http://users.pja.edu.pl/~denisjuk/al/testy/kolokwium_2012_01_29.pdf

**Motywacja do nauki - _Egzamin którego nie chcesz pisać:_**
http://users.pja.edu.pl/~denisjuk/al/testy/egzamin.pdf

# EDIT:
**Macierze:**
https://www.youtube.com/watch?v=qoaaCboDWR8&list=PLl2G2wgLAhWA5pRMSfPd9ISEaqOGQoHtk

**Comment by sebastianlew** [comment]
+1
