### ISSUE TITLE
Analiza Matematyczna

### ISSUE THREAD

**Issue by kerps1** [kerps1/Szkola#2]
**Pochodne funkcji** 
https://www.youtube.com/watch?v=H1Lj1j9a89o&list=PL778165619066E4B7
**Reguła De Hospitala** <- _AKTUALNY KOLOS_ 
https://www.youtube.com/watch?v=0EAZzzdTW-o&list=PL7F86354B1137CEB9

**Comment by kemuriCode** [comment]
WooooW 🤡 To jest świetne !!! GJ @kerps1 !!! 👊

**Comment by kemuriCode** [comment]
Jeszcze raz @kerps1 DZIĘKI !!! 🍐

**Comment by kerps1** [comment]
**Całkowanie przez części i metodą podstawiania**
https://www.youtube.com/watch?v=BuWEa949RMk 

**Co to są całki ogólnie i jak rozwiązywać**
https://www.youtube.com/watch?v=RakIc-8mysE&list=PLERRNJow7taXk0kzgxWI8koK24vk9AWis

**Comment by kemuriCode** [comment]
Oki teraz mam wszystko żeby zdać z matmy !!!➕➖➗✖️

**Comment by kerps1** [comment]
# .:INFO:.
[03.06] - Kolos z zakresu całek, na trzy nowe metody:

1. Rozkład na ułamki proste:
https://www.youtube.com/watch?v=eMhSi6gDtKo (ogolnie rozklad) 
https://www.youtube.com/watch?v=025BdPr17tM (a tu całki wiec to **legitne**)

2. Pochodna mianownika

3. Nie pamiętam, ale chyba coś było ;v
