### ISSUE TITLE
JAVA

### ISSUE THREAD

**Issue by kerps1** [kerps1/Szkola#4]

**Comment by kemuriCode** [comment]
`public class Product implements Comparable<Product>`

To mi psuje cały program 🗡  Po co jest to **implements Comparable<Product>** ?? 🤔

**Comment by kemuriCode** [comment]
![zrzut ekranu 2017-04-01 o 20 13 31](https://cloud.githubusercontent.com/assets/24705541/24581230/d95ff94c-1717-11e7-9b6b-d6278e3c3458.png)

A jak ładnie skopiuję według mnie DOBRZE xD to wyskakuje taki oto błąd😢

**Comment by kerps1** [comment]
![aaaaa](https://cloud.githubusercontent.com/assets/24704563/24585394/7bbbf486-1789-11e7-883d-c5c2d5160c42.png)
No u mnie działa normalnie, nie wiem o co biega :thinking:

**Comment by kemuriCode** [comment]
Fuck! But HOOOW!? 😩😩😩

**Comment by kemuriCode** [comment]
![zrzut ekranu 2017-04-02 o 11 33 34](https://cloud.githubusercontent.com/assets/24705541/24586025/4ef48d82-1798-11e7-8ce7-f20726b2510c.png)

Oki już mam 😁

**Comment by kerps1** [comment]
co było źle :D

**Comment by kemuriCode** [comment]
Jak tworzyłem projekt musiałem kliknąć w jakieś gówno x'D (te początkowe ustawienia 😂)

**Comment by kerps1** [comment]
# .:INFO:.
[18.06] - Projekt z cukiernią i to chyba all jak na tą chwile, poczekamy na oceny z kolosa :P.

Materiały: chcesieuczyc.pl (DANKE @WyDym!!! :clinking_glasses: )
