### ISSUE TITLE
Systemy Operacyjne

### ISSUE THREAD

**Issue by kerps1** [kerps1/Szkola#6]
# Wydarzenia:

1. 23.04.2017 - Kolos z linuxów + to co robimy na zajęciach, czyli (?)

# Materiały:

1. http://wazniak.mimuw.edu.pl/index.php?title=Strona_g%C5%82%C3%B3wna
https://szuflandia.pjwstk.edu.pl:9000/
http://leksykot.top.hell.pl/tech/bash_string

**Comment by kemuriCode** [comment]
# **C++**
https://www.wykop.pl/wpis/9719000/cpp-naukaprogramowania-programowanie-wstep-czestot/

**Pozdro**

**Comment by kerps1** [comment]
# .:INFO:.
Więc tak...

**[04.06]** - Do zrobienia wszystkie zadania oprócz tych bashowych, oczywiście to jest głównie po to żeby się nauczyć i zapytać się go gdyby miało się z czymś problem. Można też zrobić bashowe i się zapytać.

Zadania dla chętnych, którzy nie zdali basha - > to pewnie ułatwi nam zaliczenie czy coś, mówił też, że jak je zrobimy to łatwiej nam będzie na poprawie, którą prawdopodobnie zamierza zrobić:

1. Skrypt, który łączy się z katalogiem i sprawdza zmiany przeprowadzone w pliku (dodawanie czegoś, modyfikacja, usuwanie). Ma sprawdzać zmiany w katalogu, którego podamy jako argument wywoływania funkcji. Nie może on non stop skanować w pętli, zadaniem skryptu jest podłączenie sie przez sygnały.
(Zapisałem też "narzędzie", nie wiem co miałem na myśli, nie pytajcie :p) 
2. Z PDF mają być pobierane kawałki skryptu basha. (więcej nie mam, trzeba byłoby się dopytać o co mu chodziło)

**[18.06]** - Kolos z C++ (lub C, jak kto woli) z Sygnałów, Gniazd itp, wszystko jest na Szuflandii. Radził on nam żebyśmy przygotowali sobie tak zwany "makefile" - podobno jest pełno poradników w necie.
