### ISSUE TITLE
Angielski

### ISSUE THREAD

**Issue by kerps1** [kerps1/Szkola#7]
# Wydarzenia:

1. 22.04.2017 - Kolos z 3 rozdziału + Past/Present Perfect

# Materiały:

1. Słówka z tego działu + czasy

**Comment by kemuriCode** [comment]
Ma ktoś z Was chłopaki może zdjęcie testu ? 😝

**Comment by kerps1** [comment]
@WyDym Tylko ja pisałem Dymson no i niestety nie ma jak zrobić :/ Były 3 zadania, 
1. słówka te typu upgrade itp i przyporządkowanie ich pod tekst
2. czasowniki past/present perfect
3. jakieś tam słówka, ale nie wiem o co chodziło xd było podane znaczenie zdania i miałeś wstawić odpowiednie słowo
@S3baso <- Sebie też sie przyda info :D

**Comment by kerps1** [comment]
# .:INFO:.
[03.06] - Praca domowa na Angola 

![angol](https://cloud.githubusercontent.com/assets/24704563/26371721/d99c8d0a-3ffb-11e7-8863-81113f2ce66b.png)

**Comment by sebastianlew** [comment]
Thank you so much

**Comment by kemuriCode** [comment]
DANKE !!!
